### ISSUE TITLE
Unknown error on Configuration

### ISSUE THREAD

**Issue by naraic78** [jasonmadigan/ha-hkc#19]
Hello,
I am getting an 'Unknown error' on configuration setup.  I suspect that it may be mix-up in my understanding and wanted to clarify names initially to what info I've got and what I'm inputting.  For 'Alarm Code' I'm inputting the User Code.  For 'Panel Password' I'm inputting the Engineer's Code and for 'Panel ID' I'm inputting the Installation ID.  Am I correct or am I missing some info?
Thanks,
Ciarán

**Comment by jasonmadigan** [comment]
@naraic78 panel password is the password you use to login to the panel via the HKC app, not the engineer code. Hope that helps.

**Comment by daviss57** [comment]
Having the same issue. Have it up and running for a more than a month at home. Recently went to setup in my parents and find I am getting 'Unknown error'.

Think the log below is related.

Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 7 May 2024 at 23:55:35 (5 occurrences)
Last logged: 7 May 2024 at 23:58:57

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 356, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 402, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 506, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hkc_alarm/config_flow.py", line 34, in async_step_user
    is_authenticated = await self.hass.async_add_executor_job(api.check_login)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhkc/hkc_api.py", line 112, in check_login
    raise Exception('Unexpected response format from get_system_status')
Exception: Unexpected response format from get_system_status

**Comment by daviss57** [comment]
@jasonmadigan Did you have a chance to look at the log above?

**Comment by jasonmadigan** [comment]
@daviss57 apols, didn't see this. I've seen similar error with:

- Wrong credentials for one of: 
```
Panel ID: Your HKC Alarm Panel ID (same as panel ID in HKC mobile app)
Panel Password: Your HKC Alarm Panel Password (same as panel password from HKC mobile app)
Alarm Code: Your HKC Alarm Code/PIN 
```
- Or, in one case, an older panel.

I assume the panel you've got works with the new HKC mobile app?

**Comment by daviss57** [comment]
No prob, 

Will do a double check but 90% sure I've the credentials correct. Both panels work with the new app.

**Comment by jasonmadigan** [comment]
@daviss57 if you're python inclined, you can also try running the example from `pyhkc` to see if the creds are right (this integration uses it to interact with the API):

https://github.com/jasonmadigan/pyhkc#example-usage
